-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_RegCell is
  port (
    p_In: in std_logic;
    Clk: in std_logic;
    p_Out: out std_logic);
end n1Bit_RegCell;

architecture Behavioral of n1Bit_RegCell is
  signal s0: std_logic;
  signal s1: std_logic;
  signal Out_temp: std_logic;
begin
  s1 <= NOT (s0 AND NOT (Clk AND p_In));
  s0 <= NOT (NOT (Clk AND NOT p_In) AND s1);
  Out_temp <= NOT (NOT (s1 AND NOT Clk) AND NOT (Out_temp AND NOT (NOT Clk AND s0)));
  p_Out <= Out_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16Bit_AndArray is
  port (
    In_15: in std_logic;
    In_14: in std_logic;
    In_13: in std_logic;
    In_12: in std_logic;
    In_11: in std_logic;
    In_10: in std_logic;
    In_9: in std_logic;
    In_8: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    Rd: in std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_8: out std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_11: out std_logic;
    Out_10: out std_logic;
    Out_9: out std_logic;
    Out_14: out std_logic;
    Out_13: out std_logic;
    Out_12: out std_logic;
    Out_15: out std_logic);
end n16Bit_AndArray;

architecture Behavioral of n16Bit_AndArray is
begin
  Out_15 <= (In_15 AND Rd);
  Out_14 <= (In_14 AND Rd);
  Out_13 <= (In_13 AND Rd);
  Out_12 <= (In_12 AND Rd);
  Out_11 <= (In_11 AND Rd);
  Out_10 <= (In_10 AND Rd);
  Out_9 <= (In_9 AND Rd);
  Out_8 <= (In_8 AND Rd);
  Out_7 <= (In_7 AND Rd);
  Out_6 <= (In_6 AND Rd);
  Out_5 <= (In_5 AND Rd);
  Out_4 <= (In_4 AND Rd);
  Out_3 <= (In_3 AND Rd);
  Out_2 <= (In_2 AND Rd);
  Out_1 <= (In_1 AND Rd);
  Out_0 <= (In_0 AND Rd);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    In_1: in std_logic;
    Clk: in std_logic;
    Wrt: in std_logic;
    In_2: in std_logic;
    In_3: in std_logic;
    In_4: in std_logic;
    In_5: in std_logic;
    In_6: in std_logic;
    In_7: in std_logic;
    In_8: in std_logic;
    In_9: in std_logic;
    In_10: in std_logic;
    In_11: in std_logic;
    In_12: in std_logic;
    In_13: in std_logic;
    In_14: in std_logic;
    In_15: in std_logic;
    In_16: in std_logic;
    Rd: in std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic;
    Out_16: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
begin
  s0 <= (Wrt AND Clk);
  gate0: entity work.n1Bit_RegCell
    port map (
      p_In => In_1,
      Clk => s0,
      p_Out => s1);
  gate1: entity work.n1Bit_RegCell
    port map (
      p_In => In_2,
      Clk => s0,
      p_Out => s2);
  gate2: entity work.n1Bit_RegCell
    port map (
      p_In => In_3,
      Clk => s0,
      p_Out => s3);
  gate3: entity work.n1Bit_RegCell
    port map (
      p_In => In_4,
      Clk => s0,
      p_Out => s4);
  gate4: entity work.n1Bit_RegCell
    port map (
      p_In => In_5,
      Clk => s0,
      p_Out => s5);
  gate5: entity work.n1Bit_RegCell
    port map (
      p_In => In_6,
      Clk => s0,
      p_Out => s6);
  gate6: entity work.n1Bit_RegCell
    port map (
      p_In => In_7,
      Clk => s0,
      p_Out => s7);
  gate7: entity work.n1Bit_RegCell
    port map (
      p_In => In_8,
      Clk => s0,
      p_Out => s8);
  gate8: entity work.n1Bit_RegCell
    port map (
      p_In => In_9,
      Clk => s0,
      p_Out => s9);
  gate9: entity work.n1Bit_RegCell
    port map (
      p_In => In_10,
      Clk => s0,
      p_Out => s10);
  gate10: entity work.n1Bit_RegCell
    port map (
      p_In => In_11,
      Clk => s0,
      p_Out => s11);
  gate11: entity work.n1Bit_RegCell
    port map (
      p_In => In_12,
      Clk => s0,
      p_Out => s12);
  gate12: entity work.n1Bit_RegCell
    port map (
      p_In => In_13,
      Clk => s0,
      p_Out => s13);
  gate13: entity work.n1Bit_RegCell
    port map (
      p_In => In_14,
      Clk => s0,
      p_Out => s14);
  gate14: entity work.n1Bit_RegCell
    port map (
      p_In => In_15,
      Clk => s0,
      p_Out => s15);
  gate15: entity work.n1Bit_RegCell
    port map (
      p_In => In_16,
      Clk => s0,
      p_Out => s16);
  gate16: entity work.n16Bit_AndArray
    port map (
      In_15 => s16,
      In_14 => s15,
      In_13 => s14,
      In_12 => s13,
      In_11 => s12,
      In_10 => s11,
      In_9 => s10,
      In_8 => s9,
      In_7 => s8,
      In_6 => s7,
      In_5 => s6,
      In_4 => s5,
      In_3 => s4,
      In_2 => s3,
      In_1 => s2,
      In_0 => s1,
      Rd => Rd,
      Out_2 => Out_3,
      Out_1 => Out_2,
      Out_0 => Out_1,
      Out_5 => Out_6,
      Out_4 => Out_5,
      Out_3 => Out_4,
      Out_8 => Out_9,
      Out_7 => Out_8,
      Out_6 => Out_7,
      Out_11 => Out_12,
      Out_10 => Out_11,
      Out_9 => Out_10,
      Out_14 => Out_15,
      Out_13 => Out_14,
      Out_12 => Out_13,
      Out_15 => Out_16);
end Behavioral;
