-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n2_to_1_Mux is
  port (
    I_1: in std_logic;
    I_0: in std_logic;
    S_0: in std_logic;
    p_Out: out std_logic);
end n2_to_1_Mux;

architecture Behavioral of n2_to_1_Mux is
begin
  p_Out <= ((I_1 AND S_0) OR (I_0 AND NOT S_0));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    S_0: in std_logic;
    A_0: in std_logic;
    A_1: in std_logic;
    A_2: in std_logic;
    A_3: in std_logic;
    A_4: in std_logic;
    A_5: in std_logic;
    A_6: in std_logic;
    A_7: in std_logic;
    A_8: in std_logic;
    A_9: in std_logic;
    A_10: in std_logic;
    A_11: in std_logic;
    A_12: in std_logic;
    A_13: in std_logic;
    A_14: in std_logic;
    A_15: in std_logic;
    B_0: in std_logic;
    B_1: in std_logic;
    B_2: in std_logic;
    B_3: in std_logic;
    B_4: in std_logic;
    B_5: in std_logic;
    B_6: in std_logic;
    B_7: in std_logic;
    B_8: in std_logic;
    B_9: in std_logic;
    B_10: in std_logic;
    B_11: in std_logic;
    B_12: in std_logic;
    B_13: in std_logic;
    B_14: in std_logic;
    B_15: in std_logic;
    Out_0: out std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic);
end main;

architecture Behavioral of main is
begin
  gate0: entity work.n2_to_1_Mux
    port map (
      I_1 => B_0,
      I_0 => A_0,
      S_0 => S_0,
      p_Out => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => B_1,
      I_0 => A_1,
      S_0 => S_0,
      p_Out => Out_1);
  gate2: entity work.n2_to_1_Mux
    port map (
      I_1 => B_2,
      I_0 => A_2,
      S_0 => S_0,
      p_Out => Out_2);
  gate3: entity work.n2_to_1_Mux
    port map (
      I_1 => B_3,
      I_0 => A_3,
      S_0 => S_0,
      p_Out => Out_3);
  gate4: entity work.n2_to_1_Mux
    port map (
      I_1 => B_4,
      I_0 => A_4,
      S_0 => S_0,
      p_Out => Out_4);
  gate5: entity work.n2_to_1_Mux
    port map (
      I_1 => B_5,
      I_0 => A_5,
      S_0 => S_0,
      p_Out => Out_5);
  gate6: entity work.n2_to_1_Mux
    port map (
      I_1 => B_6,
      I_0 => A_6,
      S_0 => S_0,
      p_Out => Out_6);
  gate7: entity work.n2_to_1_Mux
    port map (
      I_1 => B_7,
      I_0 => A_7,
      S_0 => S_0,
      p_Out => Out_7);
  gate8: entity work.n2_to_1_Mux
    port map (
      I_1 => B_8,
      I_0 => A_8,
      S_0 => S_0,
      p_Out => Out_8);
  gate9: entity work.n2_to_1_Mux
    port map (
      I_1 => B_9,
      I_0 => A_9,
      S_0 => S_0,
      p_Out => Out_9);
  gate10: entity work.n2_to_1_Mux
    port map (
      I_1 => B_10,
      I_0 => A_10,
      S_0 => S_0,
      p_Out => Out_10);
  gate11: entity work.n2_to_1_Mux
    port map (
      I_1 => B_11,
      I_0 => A_11,
      S_0 => S_0,
      p_Out => Out_11);
  gate12: entity work.n2_to_1_Mux
    port map (
      I_1 => B_12,
      I_0 => A_12,
      S_0 => S_0,
      p_Out => Out_12);
  gate13: entity work.n2_to_1_Mux
    port map (
      I_1 => B_13,
      I_0 => A_13,
      S_0 => S_0,
      p_Out => Out_13);
  gate14: entity work.n2_to_1_Mux
    port map (
      I_1 => B_14,
      I_0 => A_14,
      S_0 => S_0,
      p_Out => Out_14);
  gate15: entity work.n2_to_1_Mux
    port map (
      I_1 => B_15,
      I_0 => A_15,
      S_0 => S_0,
      p_Out => Out_15);
end Behavioral;
