-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    In_15: in std_logic;
    In_14: in std_logic;
    In_13: in std_logic;
    In_12: in std_logic;
    In_11: in std_logic;
    In_10: in std_logic;
    In_9: in std_logic;
    In_8: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    Rd: in std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_8: out std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_11: out std_logic;
    Out_10: out std_logic;
    Out_9: out std_logic;
    Out_14: out std_logic;
    Out_13: out std_logic;
    Out_12: out std_logic;
    Out_15: out std_logic);
end main;

architecture Behavioral of main is
begin
  Out_15 <= (In_15 AND Rd);
  Out_14 <= (In_14 AND Rd);
  Out_13 <= (In_13 AND Rd);
  Out_12 <= (In_12 AND Rd);
  Out_11 <= (In_11 AND Rd);
  Out_10 <= (In_10 AND Rd);
  Out_9 <= (In_9 AND Rd);
  Out_8 <= (In_8 AND Rd);
  Out_7 <= (In_7 AND Rd);
  Out_6 <= (In_6 AND Rd);
  Out_5 <= (In_5 AND Rd);
  Out_4 <= (In_4 AND Rd);
  Out_3 <= (In_3 AND Rd);
  Out_2 <= (In_2 AND Rd);
  Out_1 <= (In_1 AND Rd);
  Out_0 <= (In_0 AND Rd);
end Behavioral;
