-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A: in std_logic;
    B: in std_logic;
    C_in: in std_logic;
    S: out std_logic;
    C_out: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR C_in);
  C_out <= ((C_in AND s0) OR (A AND B));
end Behavioral;
