-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    p_In: in std_logic;
    Clk: in std_logic;
    p_Out: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal Out_temp: std_logic;
begin
  s1 <= NOT (s0 AND NOT (Clk AND p_In));
  s0 <= NOT (NOT (Clk AND NOT p_In) AND s1);
  Out_temp <= NOT (NOT (s1 AND NOT Clk) AND NOT (Out_temp AND NOT (NOT Clk AND s0)));
  p_Out <= Out_temp;
end Behavioral;
