-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    S_1: in std_logic;
    S_0: in std_logic;
    I_3: in std_logic;
    I_2: in std_logic;
    I_1: in std_logic;
    I_0: in std_logic;
    p_Out: out std_logic);
end main;

architecture Behavioral of main is
begin
  p_Out <= (((S_1 AND S_0 AND I_3) OR (S_1 AND NOT S_0 AND I_2)) OR ((NOT S_1 AND S_0 AND I_1) OR (NOT S_1 AND NOT S_0 AND I_0)));
end Behavioral;
