-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n4_to_1_Mux is
  port (
    S_1: in std_logic;
    S_0: in std_logic;
    I_3: in std_logic;
    I_2: in std_logic;
    I_1: in std_logic;
    I_0: in std_logic;
    p_Out: out std_logic);
end n4_to_1_Mux;

architecture Behavioral of n4_to_1_Mux is
begin
  p_Out <= (((S_1 AND S_0 AND I_3) OR (S_1 AND NOT S_0 AND I_2)) OR ((NOT S_1 AND S_0 AND I_1) OR (NOT S_1 AND NOT S_0 AND I_0)));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Not_7: in std_logic;
    Not_6: in std_logic;
    Not_5: in std_logic;
    Not_4: in std_logic;
    Not_3: in std_logic;
    Not_2: in std_logic;
    Not_1: in std_logic;
    Not_0: in std_logic;
    Xor_7: in std_logic;
    Xor_6: in std_logic;
    Xor_5: in std_logic;
    Xor_4: in std_logic;
    Xor_3: in std_logic;
    Xor_2: in std_logic;
    Xor_1: in std_logic;
    Xor_0: in std_logic;
    Or_7: in std_logic;
    Or_6: in std_logic;
    Or_5: in std_logic;
    Or_4: in std_logic;
    Or_3: in std_logic;
    Or_2: in std_logic;
    Or_1: in std_logic;
    Or_0: in std_logic;
    And_7: in std_logic;
    And_6: in std_logic;
    And_5: in std_logic;
    And_4: in std_logic;
    And_3: in std_logic;
    And_2: in std_logic;
    And_1: in std_logic;
    And_0: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end main;

architecture Behavioral of main is
begin
  gate0: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_0,
      I_2 => Xor_0,
      I_1 => Or_0,
      I_0 => And_0,
      p_Out => Out_0);
  gate1: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_1,
      I_2 => Xor_1,
      I_1 => Or_1,
      I_0 => And_1,
      p_Out => Out_1);
  gate2: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_2,
      I_2 => Xor_2,
      I_1 => Or_2,
      I_0 => And_2,
      p_Out => Out_2);
  gate3: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_3,
      I_2 => Xor_3,
      I_1 => Or_3,
      I_0 => And_3,
      p_Out => Out_3);
  gate4: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_4,
      I_2 => Xor_4,
      I_1 => Or_4,
      I_0 => And_4,
      p_Out => Out_4);
  gate5: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_5,
      I_2 => Xor_5,
      I_1 => Or_5,
      I_0 => And_5,
      p_Out => Out_5);
  gate6: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_6,
      I_2 => Xor_6,
      I_1 => Or_6,
      I_0 => And_6,
      p_Out => Out_6);
  gate7: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_7,
      I_2 => Xor_7,
      I_1 => Or_7,
      I_0 => And_7,
      p_Out => Out_7);
end Behavioral;
