-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity Toggle_Arthm is
  port (
    toggle: in std_logic;
    IN_7: in std_logic;
    IN_6: in std_logic;
    IN_5: in std_logic;
    IN_4: in std_logic;
    IN_3: in std_logic;
    IN_2: in std_logic;
    IN_1: in std_logic;
    IN_0: in std_logic;
    OUT_7: out std_logic;
    OUT_6: out std_logic;
    OUT_5: out std_logic;
    OUT_4: out std_logic;
    OUT_3: out std_logic;
    OUT_2: out std_logic;
    OUT_1: out std_logic;
    OUT_0: out std_logic);
end Toggle_Arthm;

architecture Behavioral of Toggle_Arthm is
begin
  OUT_0 <= (IN_0 XOR toggle);
  OUT_1 <= (IN_1 XOR toggle);
  OUT_2 <= (IN_2 XOR toggle);
  OUT_3 <= (IN_3 XOR toggle);
  OUT_4 <= (IN_4 XOR toggle);
  OUT_5 <= (IN_5 XOR toggle);
  OUT_6 <= (IN_6 XOR toggle);
  OUT_7 <= (IN_7 XOR toggle);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_FullAdder is
  port (
    A: in std_logic;
    B: in std_logic;
    C_in: in std_logic;
    S: out std_logic;
    C_out: out std_logic);
end n1Bit_FullAdder;

architecture Behavioral of n1Bit_FullAdder is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR C_in);
  C_out <= ((C_in AND s0) OR (A AND B));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A_7: in std_logic;
    A_0: in std_logic;
    A_1: in std_logic;
    A_2: in std_logic;
    A_3: in std_logic;
    A_4: in std_logic;
    A_5: in std_logic;
    A_6: in std_logic;
    B_0: in std_logic;
    B_1: in std_logic;
    B_2: in std_logic;
    B_3: in std_logic;
    B_4: in std_logic;
    B_5: in std_logic;
    B_6: in std_logic;
    B_7: in std_logic;
    tgl: in std_logic;
    S_0: out std_logic;
    S_1: out std_logic;
    S_2: out std_logic;
    S_3: out std_logic;
    S_4: out std_logic;
    S_5: out std_logic;
    S_6: out std_logic;
    S_7: out std_logic;
    Ovf: out std_logic;
    n0_notAeqB: out std_logic;
    AleBnot_ve: out std_logic;
    AgrB: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal S_0_temp: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal S_1_temp: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal S_2_temp: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal S_3_temp: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal S_4_temp: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal S_5_temp: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal S_6_temp: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal S_7_temp: std_logic;
  signal s15: std_logic;
  signal Ovf_temp: std_logic;
  signal n0_notAeqB_temp: std_logic;
  signal s16: std_logic;
begin
  gate0: entity work.Toggle_Arthm
    port map (
      toggle => tgl,
      IN_7 => B_0,
      IN_6 => B_1,
      IN_5 => B_2,
      IN_4 => B_3,
      IN_3 => B_4,
      IN_2 => B_5,
      IN_1 => B_6,
      IN_0 => B_7,
      OUT_7 => s0,
      OUT_6 => s2,
      OUT_5 => s4,
      OUT_4 => s6,
      OUT_3 => s8,
      OUT_2 => s10,
      OUT_1 => s12,
      OUT_0 => s14);
  gate1: entity work.n1Bit_FullAdder
    port map (
      A => A_0,
      B => s0,
      C_in => tgl,
      S => S_0_temp,
      C_out => s1);
  gate2: entity work.n1Bit_FullAdder
    port map (
      A => A_1,
      B => s2,
      C_in => s1,
      S => S_1_temp,
      C_out => s3);
  gate3: entity work.n1Bit_FullAdder
    port map (
      A => A_2,
      B => s4,
      C_in => s3,
      S => S_2_temp,
      C_out => s5);
  gate4: entity work.n1Bit_FullAdder
    port map (
      A => A_3,
      B => s6,
      C_in => s5,
      S => S_3_temp,
      C_out => s7);
  gate5: entity work.n1Bit_FullAdder
    port map (
      A => A_4,
      B => s8,
      C_in => s7,
      S => S_4_temp,
      C_out => s9);
  gate6: entity work.n1Bit_FullAdder
    port map (
      A => A_5,
      B => s10,
      C_in => s9,
      S => S_5_temp,
      C_out => s11);
  gate7: entity work.n1Bit_FullAdder
    port map (
      A => A_6,
      B => s12,
      C_in => s11,
      S => S_6_temp,
      C_out => s13);
  gate8: entity work.n1Bit_FullAdder
    port map (
      A => A_7,
      B => s14,
      C_in => s13,
      S => S_7_temp,
      C_out => s15);
  Ovf_temp <= (s15 XOR s13);
  n0_notAeqB_temp <= NOT (((S_4_temp OR S_5_temp) OR (S_6_temp OR S_7_temp)) OR ((S_0_temp OR S_1_temp) OR (S_2_temp OR S_3_temp)));
  s16 <= (S_7_temp XOR Ovf_temp);
  AleBnot_ve <= (s16 AND tgl);
  AgrB <= (tgl AND NOT (s16 OR n0_notAeqB_temp));
  S_0 <= S_0_temp;
  S_1 <= S_1_temp;
  S_2 <= S_2_temp;
  S_3 <= S_3_temp;
  S_4 <= S_4_temp;
  S_5 <= S_5_temp;
  S_6 <= S_6_temp;
  S_7 <= S_7_temp;
  Ovf <= Ovf_temp;
  n0_notAeqB <= n0_notAeqB_temp;
end Behavioral;
