-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity Toggle_Arthm is
  port (
    toggle: in std_logic;
    IN_7: in std_logic;
    IN_6: in std_logic;
    IN_5: in std_logic;
    IN_4: in std_logic;
    IN_3: in std_logic;
    IN_2: in std_logic;
    IN_1: in std_logic;
    IN_0: in std_logic;
    OUT_7: out std_logic;
    OUT_6: out std_logic;
    OUT_5: out std_logic;
    OUT_4: out std_logic;
    OUT_3: out std_logic;
    OUT_2: out std_logic;
    OUT_1: out std_logic;
    OUT_0: out std_logic);
end Toggle_Arthm;

architecture Behavioral of Toggle_Arthm is
begin
  OUT_0 <= (IN_0 XOR toggle);
  OUT_1 <= (IN_1 XOR toggle);
  OUT_2 <= (IN_2 XOR toggle);
  OUT_3 <= (IN_3 XOR toggle);
  OUT_4 <= (IN_4 XOR toggle);
  OUT_5 <= (IN_5 XOR toggle);
  OUT_6 <= (IN_6 XOR toggle);
  OUT_7 <= (IN_7 XOR toggle);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_FullAdder is
  port (
    A: in std_logic;
    B: in std_logic;
    C_in: in std_logic;
    S: out std_logic;
    C_out: out std_logic);
end n1Bit_FullAdder;

architecture Behavioral of n1Bit_FullAdder is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR C_in);
  C_out <= ((C_in AND s0) OR (A AND B));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_FullAdder is
  port (
    A_7: in std_logic;
    A_0: in std_logic;
    A_1: in std_logic;
    A_2: in std_logic;
    A_3: in std_logic;
    A_4: in std_logic;
    A_5: in std_logic;
    A_6: in std_logic;
    B_0: in std_logic;
    B_1: in std_logic;
    B_2: in std_logic;
    B_3: in std_logic;
    B_4: in std_logic;
    B_5: in std_logic;
    B_6: in std_logic;
    B_7: in std_logic;
    tgl: in std_logic;
    S_0: out std_logic;
    S_1: out std_logic;
    S_2: out std_logic;
    S_3: out std_logic;
    S_4: out std_logic;
    S_5: out std_logic;
    S_6: out std_logic;
    S_7: out std_logic;
    Ovf: out std_logic;
    n0_notAeqB: out std_logic;
    AleBnot_ve: out std_logic;
    AgrB: out std_logic);
end n8Bit_FullAdder;

architecture Behavioral of n8Bit_FullAdder is
  signal s0: std_logic;
  signal S_0_temp: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal S_1_temp: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal S_2_temp: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal S_3_temp: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal S_4_temp: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal S_5_temp: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal S_6_temp: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal S_7_temp: std_logic;
  signal s15: std_logic;
  signal Ovf_temp: std_logic;
  signal n0_notAeqB_temp: std_logic;
  signal s16: std_logic;
begin
  gate0: entity work.Toggle_Arthm
    port map (
      toggle => tgl,
      IN_7 => B_0,
      IN_6 => B_1,
      IN_5 => B_2,
      IN_4 => B_3,
      IN_3 => B_4,
      IN_2 => B_5,
      IN_1 => B_6,
      IN_0 => B_7,
      OUT_7 => s0,
      OUT_6 => s2,
      OUT_5 => s4,
      OUT_4 => s6,
      OUT_3 => s8,
      OUT_2 => s10,
      OUT_1 => s12,
      OUT_0 => s14);
  gate1: entity work.n1Bit_FullAdder
    port map (
      A => A_0,
      B => s0,
      C_in => tgl,
      S => S_0_temp,
      C_out => s1);
  gate2: entity work.n1Bit_FullAdder
    port map (
      A => A_1,
      B => s2,
      C_in => s1,
      S => S_1_temp,
      C_out => s3);
  gate3: entity work.n1Bit_FullAdder
    port map (
      A => A_2,
      B => s4,
      C_in => s3,
      S => S_2_temp,
      C_out => s5);
  gate4: entity work.n1Bit_FullAdder
    port map (
      A => A_3,
      B => s6,
      C_in => s5,
      S => S_3_temp,
      C_out => s7);
  gate5: entity work.n1Bit_FullAdder
    port map (
      A => A_4,
      B => s8,
      C_in => s7,
      S => S_4_temp,
      C_out => s9);
  gate6: entity work.n1Bit_FullAdder
    port map (
      A => A_5,
      B => s10,
      C_in => s9,
      S => S_5_temp,
      C_out => s11);
  gate7: entity work.n1Bit_FullAdder
    port map (
      A => A_6,
      B => s12,
      C_in => s11,
      S => S_6_temp,
      C_out => s13);
  gate8: entity work.n1Bit_FullAdder
    port map (
      A => A_7,
      B => s14,
      C_in => s13,
      S => S_7_temp,
      C_out => s15);
  Ovf_temp <= (s15 XOR s13);
  n0_notAeqB_temp <= NOT (((S_4_temp OR S_5_temp) OR (S_6_temp OR S_7_temp)) OR ((S_0_temp OR S_1_temp) OR (S_2_temp OR S_3_temp)));
  s16 <= (S_7_temp XOR Ovf_temp);
  AleBnot_ve <= (s16 AND tgl);
  AgrB <= (tgl AND NOT (s16 OR n0_notAeqB_temp));
  S_0 <= S_0_temp;
  S_1 <= S_1_temp;
  S_2 <= S_2_temp;
  S_3 <= S_3_temp;
  S_4 <= S_4_temp;
  S_5 <= S_5_temp;
  S_6 <= S_6_temp;
  S_7 <= S_7_temp;
  Ovf <= Ovf_temp;
  n0_notAeqB <= n0_notAeqB_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n4_to_1_Mux is
  port (
    S_1: in std_logic;
    S_0: in std_logic;
    I_3: in std_logic;
    I_2: in std_logic;
    I_1: in std_logic;
    I_0: in std_logic;
    p_Out: out std_logic);
end n4_to_1_Mux;

architecture Behavioral of n4_to_1_Mux is
begin
  p_Out <= (((S_1 AND S_0 AND I_3) OR (S_1 AND NOT S_0 AND I_2)) OR ((NOT S_1 AND S_0 AND I_1) OR (NOT S_1 AND NOT S_0 AND I_0)));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_4_to_1_Mux is
  port (
    Not_7: in std_logic;
    Not_6: in std_logic;
    Not_5: in std_logic;
    Not_4: in std_logic;
    Not_3: in std_logic;
    Not_2: in std_logic;
    Not_1: in std_logic;
    Not_0: in std_logic;
    Xor_7: in std_logic;
    Xor_6: in std_logic;
    Xor_5: in std_logic;
    Xor_4: in std_logic;
    Xor_3: in std_logic;
    Xor_2: in std_logic;
    Xor_1: in std_logic;
    Xor_0: in std_logic;
    Or_7: in std_logic;
    Or_6: in std_logic;
    Or_5: in std_logic;
    Or_4: in std_logic;
    Or_3: in std_logic;
    Or_2: in std_logic;
    Or_1: in std_logic;
    Or_0: in std_logic;
    And_7: in std_logic;
    And_6: in std_logic;
    And_5: in std_logic;
    And_4: in std_logic;
    And_3: in std_logic;
    And_2: in std_logic;
    And_1: in std_logic;
    And_0: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end n8Bit_4_to_1_Mux;

architecture Behavioral of n8Bit_4_to_1_Mux is
begin
  gate0: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_0,
      I_2 => Xor_0,
      I_1 => Or_0,
      I_0 => And_0,
      p_Out => Out_0);
  gate1: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_1,
      I_2 => Xor_1,
      I_1 => Or_1,
      I_0 => And_1,
      p_Out => Out_1);
  gate2: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_2,
      I_2 => Xor_2,
      I_1 => Or_2,
      I_0 => And_2,
      p_Out => Out_2);
  gate3: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_3,
      I_2 => Xor_3,
      I_1 => Or_3,
      I_0 => And_3,
      p_Out => Out_3);
  gate4: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_4,
      I_2 => Xor_4,
      I_1 => Or_4,
      I_0 => And_4,
      p_Out => Out_4);
  gate5: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_5,
      I_2 => Xor_5,
      I_1 => Or_5,
      I_0 => And_5,
      p_Out => Out_5);
  gate6: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_6,
      I_2 => Xor_6,
      I_1 => Or_6,
      I_0 => And_6,
      p_Out => Out_6);
  gate7: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_7,
      I_2 => Xor_7,
      I_1 => Or_7,
      I_0 => And_7,
      p_Out => Out_7);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity BitWise_Oprtn is
  port (
    A_7: in std_logic;
    A_6: in std_logic;
    A_5: in std_logic;
    A_4: in std_logic;
    A_3: in std_logic;
    A_2: in std_logic;
    A_1: in std_logic;
    A_0: in std_logic;
    B_7: in std_logic;
    B_6: in std_logic;
    B_5: in std_logic;
    B_4: in std_logic;
    B_3: in std_logic;
    B_2: in std_logic;
    B_1: in std_logic;
    B_0: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end BitWise_Oprtn;

architecture Behavioral of BitWise_Oprtn is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
begin
  s0 <= NOT A_7;
  s1 <= NOT A_6;
  s2 <= NOT A_5;
  s3 <= NOT A_4;
  s4 <= NOT A_3;
  s5 <= NOT A_2;
  s6 <= NOT A_1;
  s7 <= NOT A_0;
  s8 <= (A_7 XOR B_7);
  s9 <= (A_6 XOR B_6);
  s10 <= (A_5 XOR B_5);
  s11 <= (A_4 XOR B_4);
  s12 <= (A_3 XOR B_3);
  s13 <= (A_2 XOR B_2);
  s14 <= (A_1 XOR B_1);
  s15 <= (A_0 XOR B_0);
  s16 <= (A_7 OR B_7);
  s17 <= (A_6 OR B_6);
  s18 <= (A_5 OR B_5);
  s19 <= (A_4 OR B_4);
  s20 <= (A_3 OR B_3);
  s21 <= (A_2 OR B_2);
  s22 <= (A_1 OR B_1);
  s23 <= (A_0 OR B_0);
  s24 <= (A_7 AND B_7);
  s25 <= (A_6 AND B_6);
  s26 <= (A_5 AND B_5);
  s27 <= (A_4 AND B_4);
  s28 <= (A_3 AND B_3);
  s29 <= (A_2 AND B_2);
  s30 <= (A_1 AND B_1);
  s31 <= (A_0 AND B_0);
  gate0: entity work.n8Bit_4_to_1_Mux
    port map (
      Not_7 => s0,
      Not_6 => s1,
      Not_5 => s2,
      Not_4 => s3,
      Not_3 => s4,
      Not_2 => s5,
      Not_1 => s6,
      Not_0 => s7,
      Xor_7 => s8,
      Xor_6 => s9,
      Xor_5 => s10,
      Xor_4 => s11,
      Xor_3 => s12,
      Xor_2 => s13,
      Xor_1 => s14,
      Xor_0 => s15,
      Or_7 => s16,
      Or_6 => s17,
      Or_5 => s18,
      Or_4 => s19,
      Or_3 => s20,
      Or_2 => s21,
      Or_1 => s22,
      Or_0 => s23,
      And_7 => s24,
      And_6 => s25,
      And_5 => s26,
      And_4 => s27,
      And_3 => s28,
      And_2 => s29,
      And_1 => s30,
      And_0 => s31,
      S_1 => S_1,
      S_0 => S_0,
      Out_7 => Out_7,
      Out_6 => Out_6,
      Out_5 => Out_5,
      Out_4 => Out_4,
      Out_3 => Out_3,
      Out_2 => Out_2,
      Out_1 => Out_1,
      Out_0 => Out_0);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n2_to_1_Mux is
  port (
    I_1: in std_logic;
    I_0: in std_logic;
    S_0: in std_logic;
    p_Out: out std_logic);
end n2_to_1_Mux;

architecture Behavioral of n2_to_1_Mux is
begin
  p_Out <= ((I_1 AND S_0) OR (I_0 AND NOT S_0));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_2_to_1_Mux is
  port (
    m_7: in std_logic;
    m_6: in std_logic;
    m_5: in std_logic;
    m_4: in std_logic;
    m_3: in std_logic;
    m_2: in std_logic;
    m_1: in std_logic;
    m_0: in std_logic;
    d_7: in std_logic;
    d_6: in std_logic;
    B_5: in std_logic;
    d_4: in std_logic;
    d_3: in std_logic;
    d_2: in std_logic;
    d_1: in std_logic;
    d_0: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end n8Bit_2_to_1_Mux;

architecture Behavioral of n8Bit_2_to_1_Mux is
begin
  gate0: entity work.n2_to_1_Mux
    port map (
      I_1 => d_0,
      I_0 => m_0,
      S_0 => S_0,
      p_Out => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => d_1,
      I_0 => m_1,
      S_0 => S_0,
      p_Out => Out_1);
  gate2: entity work.n2_to_1_Mux
    port map (
      I_1 => d_2,
      I_0 => m_2,
      S_0 => S_0,
      p_Out => Out_2);
  gate3: entity work.n2_to_1_Mux
    port map (
      I_1 => d_3,
      I_0 => m_3,
      S_0 => S_0,
      p_Out => Out_3);
  gate4: entity work.n2_to_1_Mux
    port map (
      I_1 => d_4,
      I_0 => m_4,
      S_0 => S_0,
      p_Out => Out_4);
  gate5: entity work.n2_to_1_Mux
    port map (
      I_1 => B_5,
      I_0 => m_5,
      S_0 => S_0,
      p_Out => Out_5);
  gate6: entity work.n2_to_1_Mux
    port map (
      I_1 => d_6,
      I_0 => m_6,
      S_0 => S_0,
      p_Out => Out_6);
  gate7: entity work.n2_to_1_Mux
    port map (
      I_1 => d_7,
      I_0 => m_7,
      S_0 => S_0,
      p_Out => Out_7);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity Shifter is
  port (
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    M_Ovf: out std_logic;
    Rmdr: out std_logic);
end Shifter;

architecture Behavioral of Shifter is
  signal s0: std_logic;
begin
  gate0: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => In_6,
      m_6 => In_5,
      m_5 => In_4,
      m_4 => In_3,
      m_3 => In_2,
      m_2 => In_1,
      m_1 => In_0,
      m_0 => '0',
      d_7 => '0',
      d_6 => In_7,
      B_5 => In_6,
      d_4 => In_5,
      d_3 => In_4,
      d_2 => In_3,
      d_1 => In_2,
      d_0 => In_1,
      S_0 => S_0,
      Out_7 => Out_7,
      Out_6 => Out_6,
      Out_5 => Out_5,
      Out_4 => Out_4,
      Out_3 => Out_3,
      Out_2 => Out_2,
      Out_1 => Out_1,
      Out_0 => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => In_0,
      I_0 => In_7,
      S_0 => S_0,
      p_Out => s0);
  M_Ovf <= (s0 AND In_7);
  Rmdr <= (s0 AND In_0);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    B_7: in std_logic;
    B_6: in std_logic;
    B_5: in std_logic;
    B_4: in std_logic;
    B_3: in std_logic;
    B_2: in std_logic;
    B_1: in std_logic;
    B_0: in std_logic;
    A_7: in std_logic;
    A_6: in std_logic;
    A_5: in std_logic;
    A_4: in std_logic;
    A_3: in std_logic;
    A_2: in std_logic;
    A_1: in std_logic;
    A_0: in std_logic;
    D_5: in std_logic;
    D_4: in std_logic;
    D_3: in std_logic;
    D_2: in std_logic;
    D_1: in std_logic;
    D_0: in std_logic;
    D_6: in std_logic;
    D_7: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    Ovf: out std_logic;
    n0notAeqB: out std_logic;
    venotAleB: out std_logic;
    AgrB: out std_logic;
    M_Ovf: out std_logic;
    Rmdr: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
  signal s32: std_logic;
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
  signal s37: std_logic;
  signal s38: std_logic;
  signal s39: std_logic;
begin
  gate0: entity work.n8Bit_FullAdder
    port map (
      A_7 => A_7,
      A_0 => A_0,
      A_1 => A_1,
      A_2 => A_2,
      A_3 => A_3,
      A_4 => A_4,
      A_5 => A_5,
      A_6 => A_6,
      B_0 => B_0,
      B_1 => B_1,
      B_2 => B_2,
      B_3 => B_3,
      B_4 => B_4,
      B_5 => B_5,
      B_6 => B_6,
      B_7 => B_7,
      tgl => D_6,
      S_0 => s0,
      S_1 => s1,
      S_2 => s2,
      S_3 => s3,
      S_4 => s4,
      S_5 => s5,
      S_6 => s6,
      S_7 => s7,
      Ovf => Ovf,
      n0_notAeqB => n0notAeqB,
      AleBnot_ve => venotAleB,
      AgrB => AgrB);
  gate1: entity work.BitWise_Oprtn
    port map (
      A_7 => A_7,
      A_6 => A_6,
      A_5 => A_5,
      A_4 => A_4,
      A_3 => A_3,
      A_2 => A_2,
      A_1 => A_1,
      A_0 => A_0,
      B_7 => B_7,
      B_6 => B_6,
      B_5 => B_5,
      B_4 => B_4,
      B_3 => B_3,
      B_2 => B_2,
      B_1 => B_1,
      B_0 => B_0,
      S_1 => D_5,
      S_0 => D_4,
      Out_7 => s8,
      Out_6 => s9,
      Out_5 => s10,
      Out_4 => s11,
      Out_3 => s12,
      Out_2 => s13,
      Out_1 => s14,
      Out_0 => s15);
  gate2: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => s7,
      m_6 => s6,
      m_5 => s5,
      m_4 => s4,
      m_3 => s3,
      m_2 => s2,
      m_1 => s1,
      m_0 => s0,
      d_7 => s8,
      d_6 => s9,
      B_5 => s10,
      d_4 => s11,
      d_3 => s12,
      d_2 => s13,
      d_1 => s14,
      d_0 => s15,
      S_0 => D_3,
      Out_7 => s16,
      Out_6 => s17,
      Out_5 => s18,
      Out_4 => s19,
      Out_3 => s20,
      Out_2 => s21,
      Out_1 => s22,
      Out_0 => s23);
  gate3: entity work.Shifter
    port map (
      In_3 => s20,
      In_2 => s21,
      In_1 => s22,
      In_0 => s23,
      In_7 => s16,
      In_6 => s17,
      In_5 => s18,
      In_4 => s19,
      S_0 => D_2,
      Out_7 => s24,
      Out_6 => s25,
      Out_5 => s26,
      Out_4 => s27,
      Out_3 => s28,
      Out_2 => s29,
      Out_1 => s30,
      Out_0 => s31,
      M_Ovf => M_Ovf,
      Rmdr => Rmdr);
  gate4: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => s7,
      m_6 => s6,
      m_5 => s5,
      m_4 => s4,
      m_3 => s3,
      m_2 => s2,
      m_1 => s1,
      m_0 => s0,
      d_7 => s24,
      d_6 => s25,
      B_5 => s26,
      d_4 => s27,
      d_3 => s28,
      d_2 => s29,
      d_1 => s30,
      d_0 => s31,
      S_0 => D_1,
      Out_7 => s32,
      Out_6 => s33,
      Out_5 => s34,
      Out_4 => s35,
      Out_3 => s36,
      Out_2 => s37,
      Out_1 => s38,
      Out_0 => s39);
  gate5: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => s32,
      m_6 => s33,
      m_5 => s34,
      m_4 => s35,
      m_3 => s36,
      m_2 => s37,
      m_1 => s38,
      m_0 => s39,
      d_7 => s8,
      d_6 => s9,
      B_5 => s10,
      d_4 => s11,
      d_3 => s12,
      d_2 => s13,
      d_1 => s14,
      d_0 => s15,
      S_0 => D_0,
      Out_7 => Out_7,
      Out_6 => Out_6,
      Out_5 => Out_5,
      Out_4 => Out_4,
      Out_3 => Out_3,
      Out_2 => Out_2,
      Out_1 => Out_1,
      Out_0 => Out_0);
end Behavioral;
