-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n4_to_1_Mux is
  port (
    S_1: in std_logic;
    S_0: in std_logic;
    I_3: in std_logic;
    I_2: in std_logic;
    I_1: in std_logic;
    I_0: in std_logic;
    p_Out: out std_logic);
end n4_to_1_Mux;

architecture Behavioral of n4_to_1_Mux is
begin
  p_Out <= (((S_1 AND S_0 AND I_3) OR (S_1 AND NOT S_0 AND I_2)) OR ((NOT S_1 AND S_0 AND I_1) OR (NOT S_1 AND NOT S_0 AND I_0)));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_4_to_1_Mux is
  port (
    Not_7: in std_logic;
    Not_6: in std_logic;
    Not_5: in std_logic;
    Not_4: in std_logic;
    Not_3: in std_logic;
    Not_2: in std_logic;
    Not_1: in std_logic;
    Not_0: in std_logic;
    Xor_7: in std_logic;
    Xor_6: in std_logic;
    Xor_5: in std_logic;
    Xor_4: in std_logic;
    Xor_3: in std_logic;
    Xor_2: in std_logic;
    Xor_1: in std_logic;
    Xor_0: in std_logic;
    Or_7: in std_logic;
    Or_6: in std_logic;
    Or_5: in std_logic;
    Or_4: in std_logic;
    Or_3: in std_logic;
    Or_2: in std_logic;
    Or_1: in std_logic;
    Or_0: in std_logic;
    And_7: in std_logic;
    And_6: in std_logic;
    And_5: in std_logic;
    And_4: in std_logic;
    And_3: in std_logic;
    And_2: in std_logic;
    And_1: in std_logic;
    And_0: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end n8Bit_4_to_1_Mux;

architecture Behavioral of n8Bit_4_to_1_Mux is
begin
  gate0: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_0,
      I_2 => Xor_0,
      I_1 => Or_0,
      I_0 => And_0,
      p_Out => Out_0);
  gate1: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_1,
      I_2 => Xor_1,
      I_1 => Or_1,
      I_0 => And_1,
      p_Out => Out_1);
  gate2: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_2,
      I_2 => Xor_2,
      I_1 => Or_2,
      I_0 => And_2,
      p_Out => Out_2);
  gate3: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_3,
      I_2 => Xor_3,
      I_1 => Or_3,
      I_0 => And_3,
      p_Out => Out_3);
  gate4: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_4,
      I_2 => Xor_4,
      I_1 => Or_4,
      I_0 => And_4,
      p_Out => Out_4);
  gate5: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_5,
      I_2 => Xor_5,
      I_1 => Or_5,
      I_0 => And_5,
      p_Out => Out_5);
  gate6: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_6,
      I_2 => Xor_6,
      I_1 => Or_6,
      I_0 => And_6,
      p_Out => Out_6);
  gate7: entity work.n4_to_1_Mux
    port map (
      S_1 => S_1,
      S_0 => S_0,
      I_3 => Not_7,
      I_2 => Xor_7,
      I_1 => Or_7,
      I_0 => And_7,
      p_Out => Out_7);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A_7: in std_logic;
    A_6: in std_logic;
    A_5: in std_logic;
    A_4: in std_logic;
    A_3: in std_logic;
    A_2: in std_logic;
    A_1: in std_logic;
    A_0: in std_logic;
    B_7: in std_logic;
    B_6: in std_logic;
    B_5: in std_logic;
    B_4: in std_logic;
    B_3: in std_logic;
    B_2: in std_logic;
    B_1: in std_logic;
    B_0: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
begin
  s0 <= NOT A_7;
  s1 <= NOT A_6;
  s2 <= NOT A_5;
  s3 <= NOT A_4;
  s4 <= NOT A_3;
  s5 <= NOT A_2;
  s6 <= NOT A_1;
  s7 <= NOT A_0;
  s8 <= (A_7 XOR B_7);
  s9 <= (A_6 XOR B_6);
  s10 <= (A_5 XOR B_5);
  s11 <= (A_4 XOR B_4);
  s12 <= (A_3 XOR B_3);
  s13 <= (A_2 XOR B_2);
  s14 <= (A_1 XOR B_1);
  s15 <= (A_0 XOR B_0);
  s16 <= (A_7 OR B_7);
  s17 <= (A_6 OR B_6);
  s18 <= (A_5 OR B_5);
  s19 <= (A_4 OR B_4);
  s20 <= (A_3 OR B_3);
  s21 <= (A_2 OR B_2);
  s22 <= (A_1 OR B_1);
  s23 <= (A_0 OR B_0);
  s24 <= (A_7 AND B_7);
  s25 <= (A_6 AND B_6);
  s26 <= (A_5 AND B_5);
  s27 <= (A_4 AND B_4);
  s28 <= (A_3 AND B_3);
  s29 <= (A_2 AND B_2);
  s30 <= (A_1 AND B_1);
  s31 <= (A_0 AND B_0);
  gate0: entity work.n8Bit_4_to_1_Mux
    port map (
      Not_7 => s0,
      Not_6 => s1,
      Not_5 => s2,
      Not_4 => s3,
      Not_3 => s4,
      Not_2 => s5,
      Not_1 => s6,
      Not_0 => s7,
      Xor_7 => s8,
      Xor_6 => s9,
      Xor_5 => s10,
      Xor_4 => s11,
      Xor_3 => s12,
      Xor_2 => s13,
      Xor_1 => s14,
      Xor_0 => s15,
      Or_7 => s16,
      Or_6 => s17,
      Or_5 => s18,
      Or_4 => s19,
      Or_3 => s20,
      Or_2 => s21,
      Or_1 => s22,
      Or_0 => s23,
      And_7 => s24,
      And_6 => s25,
      And_5 => s26,
      And_4 => s27,
      And_3 => s28,
      And_2 => s29,
      And_1 => s30,
      And_0 => s31,
      S_1 => S_1,
      S_0 => S_0,
      Out_7 => Out_7,
      Out_6 => Out_6,
      Out_5 => Out_5,
      Out_4 => Out_4,
      Out_3 => Out_3,
      Out_2 => Out_2,
      Out_1 => Out_1,
      Out_0 => Out_0);
end Behavioral;
