-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_RegCell is
  port (
    p_In: in std_logic;
    Clk: in std_logic;
    p_Out: out std_logic);
end n1Bit_RegCell;

architecture Behavioral of n1Bit_RegCell is
  signal s0: std_logic;
  signal s1: std_logic;
  signal Out_temp: std_logic;
begin
  s1 <= NOT (s0 AND NOT (Clk AND p_In));
  s0 <= NOT (NOT (Clk AND NOT p_In) AND s1);
  Out_temp <= NOT (NOT (s1 AND NOT Clk) AND NOT (Out_temp AND NOT (NOT Clk AND s0)));
  p_Out <= Out_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16Bit_AndArray is
  port (
    In_15: in std_logic;
    In_14: in std_logic;
    In_13: in std_logic;
    In_12: in std_logic;
    In_11: in std_logic;
    In_10: in std_logic;
    In_9: in std_logic;
    In_8: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    Rd: in std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_8: out std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_11: out std_logic;
    Out_10: out std_logic;
    Out_9: out std_logic;
    Out_14: out std_logic;
    Out_13: out std_logic;
    Out_12: out std_logic;
    Out_15: out std_logic);
end n16Bit_AndArray;

architecture Behavioral of n16Bit_AndArray is
begin
  Out_15 <= (In_15 AND Rd);
  Out_14 <= (In_14 AND Rd);
  Out_13 <= (In_13 AND Rd);
  Out_12 <= (In_12 AND Rd);
  Out_11 <= (In_11 AND Rd);
  Out_10 <= (In_10 AND Rd);
  Out_9 <= (In_9 AND Rd);
  Out_8 <= (In_8 AND Rd);
  Out_7 <= (In_7 AND Rd);
  Out_6 <= (In_6 AND Rd);
  Out_5 <= (In_5 AND Rd);
  Out_4 <= (In_4 AND Rd);
  Out_3 <= (In_3 AND Rd);
  Out_2 <= (In_2 AND Rd);
  Out_1 <= (In_1 AND Rd);
  Out_0 <= (In_0 AND Rd);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16bit_Reg is
  port (
    In_1: in std_logic;
    Clk: in std_logic;
    Wrt: in std_logic;
    In_2: in std_logic;
    In_3: in std_logic;
    In_4: in std_logic;
    In_5: in std_logic;
    In_6: in std_logic;
    In_7: in std_logic;
    In_8: in std_logic;
    In_9: in std_logic;
    In_10: in std_logic;
    In_11: in std_logic;
    In_12: in std_logic;
    In_13: in std_logic;
    In_14: in std_logic;
    In_15: in std_logic;
    In_16: in std_logic;
    Rd: in std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic;
    Out_16: out std_logic);
end n16bit_Reg;

architecture Behavioral of n16bit_Reg is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
begin
  s0 <= (Wrt AND Clk);
  gate0: entity work.n1Bit_RegCell
    port map (
      p_In => In_1,
      Clk => s0,
      p_Out => s1);
  gate1: entity work.n1Bit_RegCell
    port map (
      p_In => In_2,
      Clk => s0,
      p_Out => s2);
  gate2: entity work.n1Bit_RegCell
    port map (
      p_In => In_3,
      Clk => s0,
      p_Out => s3);
  gate3: entity work.n1Bit_RegCell
    port map (
      p_In => In_4,
      Clk => s0,
      p_Out => s4);
  gate4: entity work.n1Bit_RegCell
    port map (
      p_In => In_5,
      Clk => s0,
      p_Out => s5);
  gate5: entity work.n1Bit_RegCell
    port map (
      p_In => In_6,
      Clk => s0,
      p_Out => s6);
  gate6: entity work.n1Bit_RegCell
    port map (
      p_In => In_7,
      Clk => s0,
      p_Out => s7);
  gate7: entity work.n1Bit_RegCell
    port map (
      p_In => In_8,
      Clk => s0,
      p_Out => s8);
  gate8: entity work.n1Bit_RegCell
    port map (
      p_In => In_9,
      Clk => s0,
      p_Out => s9);
  gate9: entity work.n1Bit_RegCell
    port map (
      p_In => In_10,
      Clk => s0,
      p_Out => s10);
  gate10: entity work.n1Bit_RegCell
    port map (
      p_In => In_11,
      Clk => s0,
      p_Out => s11);
  gate11: entity work.n1Bit_RegCell
    port map (
      p_In => In_12,
      Clk => s0,
      p_Out => s12);
  gate12: entity work.n1Bit_RegCell
    port map (
      p_In => In_13,
      Clk => s0,
      p_Out => s13);
  gate13: entity work.n1Bit_RegCell
    port map (
      p_In => In_14,
      Clk => s0,
      p_Out => s14);
  gate14: entity work.n1Bit_RegCell
    port map (
      p_In => In_15,
      Clk => s0,
      p_Out => s15);
  gate15: entity work.n1Bit_RegCell
    port map (
      p_In => In_16,
      Clk => s0,
      p_Out => s16);
  gate16: entity work.n16Bit_AndArray
    port map (
      In_15 => s16,
      In_14 => s15,
      In_13 => s14,
      In_12 => s13,
      In_11 => s12,
      In_10 => s11,
      In_9 => s10,
      In_8 => s9,
      In_7 => s8,
      In_6 => s7,
      In_5 => s6,
      In_4 => s5,
      In_3 => s4,
      In_2 => s3,
      In_1 => s2,
      In_0 => s1,
      Rd => Rd,
      Out_2 => Out_3,
      Out_1 => Out_2,
      Out_0 => Out_1,
      Out_5 => Out_6,
      Out_4 => Out_5,
      Out_3 => Out_4,
      Out_8 => Out_9,
      Out_7 => Out_8,
      Out_6 => Out_7,
      Out_11 => Out_12,
      Out_10 => Out_11,
      Out_9 => Out_10,
      Out_14 => Out_15,
      Out_13 => Out_14,
      Out_12 => Out_13,
      Out_15 => Out_16);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n2_to_1_Mux is
  port (
    I_1: in std_logic;
    I_0: in std_logic;
    S_0: in std_logic;
    p_Out: out std_logic);
end n2_to_1_Mux;

architecture Behavioral of n2_to_1_Mux is
begin
  p_Out <= ((I_1 AND S_0) OR (I_0 AND NOT S_0));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_2_to_1_Mux is
  port (
    m_7: in std_logic;
    m_6: in std_logic;
    m_5: in std_logic;
    m_4: in std_logic;
    m_3: in std_logic;
    m_2: in std_logic;
    m_1: in std_logic;
    m_0: in std_logic;
    d_7: in std_logic;
    d_6: in std_logic;
    B_5: in std_logic;
    d_4: in std_logic;
    d_3: in std_logic;
    d_2: in std_logic;
    d_1: in std_logic;
    d_0: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end n8Bit_2_to_1_Mux;

architecture Behavioral of n8Bit_2_to_1_Mux is
begin
  gate0: entity work.n2_to_1_Mux
    port map (
      I_1 => d_0,
      I_0 => m_0,
      S_0 => S_0,
      p_Out => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => d_1,
      I_0 => m_1,
      S_0 => S_0,
      p_Out => Out_1);
  gate2: entity work.n2_to_1_Mux
    port map (
      I_1 => d_2,
      I_0 => m_2,
      S_0 => S_0,
      p_Out => Out_2);
  gate3: entity work.n2_to_1_Mux
    port map (
      I_1 => d_3,
      I_0 => m_3,
      S_0 => S_0,
      p_Out => Out_3);
  gate4: entity work.n2_to_1_Mux
    port map (
      I_1 => d_4,
      I_0 => m_4,
      S_0 => S_0,
      p_Out => Out_4);
  gate5: entity work.n2_to_1_Mux
    port map (
      I_1 => B_5,
      I_0 => m_5,
      S_0 => S_0,
      p_Out => Out_5);
  gate6: entity work.n2_to_1_Mux
    port map (
      I_1 => d_6,
      I_0 => m_6,
      S_0 => S_0,
      p_Out => Out_6);
  gate7: entity work.n2_to_1_Mux
    port map (
      I_1 => d_7,
      I_0 => m_7,
      S_0 => S_0,
      p_Out => Out_7);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_FullAdder is
  port (
    A: in std_logic;
    B: in std_logic;
    C_in: in std_logic;
    S: out std_logic;
    C_out: out std_logic);
end n1Bit_FullAdder;

architecture Behavioral of n1Bit_FullAdder is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR C_in);
  C_out <= ((C_in AND s0) OR (A AND B));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Jmp: in std_logic;
    Clk: in std_logic;
    J_0: in std_logic;
    J_1: in std_logic;
    J_2: in std_logic;
    J_3: in std_logic;
    J_4: in std_logic;
    J_5: in std_logic;
    J_6: in std_logic;
    J_7: in std_logic;
    J_8: in std_logic;
    J_9: in std_logic;
    J_10: in std_logic;
    J_11: in std_logic;
    J_12: in std_logic;
    J_13: in std_logic;
    J_14: in std_logic;
    J_15: in std_logic;
    C_0: out std_logic;
    C_1: out std_logic;
    C_2: out std_logic;
    C_3: out std_logic;
    C_4: out std_logic;
    C_5: out std_logic;
    C_6: out std_logic;
    C_7: out std_logic;
    C_8: out std_logic;
    C_9: out std_logic;
    C_10: out std_logic;
    C_11: out std_logic;
    C_12: out std_logic;
    C_13: out std_logic;
    C_14: out std_logic;
    C_15: out std_logic);
end main;

architecture Behavioral of main is
  signal C_0_temp: std_logic;
  signal s0: std_logic;
  signal s1: std_logic;
  signal C_1_temp: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal C_2_temp: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal C_3_temp: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal C_4_temp: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal C_5_temp: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal C_6_temp: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal C_7_temp: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal C_8_temp: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal C_9_temp: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal C_10_temp: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal C_11_temp: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal C_12_temp: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal C_13_temp: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal C_14_temp: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal C_15_temp: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
  signal s32: std_logic;
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
  signal s37: std_logic;
  signal s38: std_logic;
  signal s39: std_logic;
  signal s40: std_logic;
  signal s41: std_logic;
  signal s42: std_logic;
  signal s43: std_logic;
  signal s44: std_logic;
  signal s45: std_logic;
  signal s46: std_logic;
begin
  gate0: entity work.n16bit_Reg
    port map (
      In_1 => s31,
      Clk => Clk,
      Wrt => '1',
      In_2 => s32,
      In_3 => s33,
      In_4 => s34,
      In_5 => s35,
      In_6 => s36,
      In_7 => s37,
      In_8 => s38,
      In_9 => s39,
      In_10 => s40,
      In_11 => s41,
      In_12 => s42,
      In_13 => s43,
      In_14 => s44,
      In_15 => s45,
      In_16 => s46,
      Rd => '1',
      Out_1 => C_0_temp,
      Out_2 => C_1_temp,
      Out_3 => C_2_temp,
      Out_4 => C_3_temp,
      Out_5 => C_4_temp,
      Out_6 => C_5_temp,
      Out_7 => C_6_temp,
      Out_8 => C_7_temp,
      Out_9 => C_8_temp,
      Out_10 => C_9_temp,
      Out_11 => C_10_temp,
      Out_12 => C_11_temp,
      Out_13 => C_12_temp,
      Out_14 => C_13_temp,
      Out_15 => C_14_temp,
      Out_16 => C_15_temp);
  gate1: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => s14,
      m_6 => s12,
      m_5 => s10,
      m_4 => s8,
      m_3 => s6,
      m_2 => s4,
      m_1 => s2,
      m_0 => s0,
      d_7 => J_7,
      d_6 => J_6,
      B_5 => J_5,
      d_4 => J_4,
      d_3 => J_3,
      d_2 => J_2,
      d_1 => J_1,
      d_0 => J_0,
      S_0 => Jmp,
      Out_7 => s38,
      Out_6 => s37,
      Out_5 => s36,
      Out_4 => s35,
      Out_3 => s34,
      Out_2 => s33,
      Out_1 => s32,
      Out_0 => s31);
  gate2: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => s30,
      m_6 => s28,
      m_5 => s26,
      m_4 => s24,
      m_3 => s22,
      m_2 => s20,
      m_1 => s18,
      m_0 => s16,
      d_7 => J_15,
      d_6 => J_14,
      B_5 => J_13,
      d_4 => J_12,
      d_3 => J_11,
      d_2 => J_10,
      d_1 => J_9,
      d_0 => J_8,
      S_0 => Jmp,
      Out_7 => s46,
      Out_6 => s45,
      Out_5 => s44,
      Out_4 => s43,
      Out_3 => s42,
      Out_2 => s41,
      Out_1 => s40,
      Out_0 => s39);
  gate3: entity work.n1Bit_FullAdder
    port map (
      A => C_0_temp,
      B => '1',
      C_in => '0',
      S => s0,
      C_out => s1);
  gate4: entity work.n1Bit_FullAdder
    port map (
      A => C_1_temp,
      B => '0',
      C_in => s1,
      S => s2,
      C_out => s3);
  gate5: entity work.n1Bit_FullAdder
    port map (
      A => C_2_temp,
      B => '0',
      C_in => s3,
      S => s4,
      C_out => s5);
  gate6: entity work.n1Bit_FullAdder
    port map (
      A => C_3_temp,
      B => '0',
      C_in => s5,
      S => s6,
      C_out => s7);
  gate7: entity work.n1Bit_FullAdder
    port map (
      A => C_4_temp,
      B => '0',
      C_in => s7,
      S => s8,
      C_out => s9);
  gate8: entity work.n1Bit_FullAdder
    port map (
      A => C_5_temp,
      B => '0',
      C_in => s9,
      S => s10,
      C_out => s11);
  gate9: entity work.n1Bit_FullAdder
    port map (
      A => C_6_temp,
      B => '0',
      C_in => s11,
      S => s12,
      C_out => s13);
  gate10: entity work.n1Bit_FullAdder
    port map (
      A => C_7_temp,
      B => '0',
      C_in => s13,
      S => s14,
      C_out => s15);
  gate11: entity work.n1Bit_FullAdder
    port map (
      A => C_8_temp,
      B => '0',
      C_in => s15,
      S => s16,
      C_out => s17);
  gate12: entity work.n1Bit_FullAdder
    port map (
      A => C_9_temp,
      B => '0',
      C_in => s17,
      S => s18,
      C_out => s19);
  gate13: entity work.n1Bit_FullAdder
    port map (
      A => C_10_temp,
      B => '0',
      C_in => s19,
      S => s20,
      C_out => s21);
  gate14: entity work.n1Bit_FullAdder
    port map (
      A => C_11_temp,
      B => '0',
      C_in => s21,
      S => s22,
      C_out => s23);
  gate15: entity work.n1Bit_FullAdder
    port map (
      A => C_12_temp,
      B => '0',
      C_in => s23,
      S => s24,
      C_out => s25);
  gate16: entity work.n1Bit_FullAdder
    port map (
      A => C_13_temp,
      B => '0',
      C_in => s25,
      S => s26,
      C_out => s27);
  gate17: entity work.n1Bit_FullAdder
    port map (
      A => C_14_temp,
      B => '0',
      C_in => s27,
      S => s28,
      C_out => s29);
  gate18: entity work.n1Bit_FullAdder
    port map (
      A => C_15_temp,
      B => '0',
      C_in => s29,
      S => s30);
  C_0 <= C_0_temp;
  C_1 <= C_1_temp;
  C_2 <= C_2_temp;
  C_3 <= C_3_temp;
  C_4 <= C_4_temp;
  C_5 <= C_5_temp;
  C_6 <= C_6_temp;
  C_7 <= C_7_temp;
  C_8 <= C_8_temp;
  C_9 <= C_9_temp;
  C_10 <= C_10_temp;
  C_11 <= C_11_temp;
  C_12 <= C_12_temp;
  C_13 <= C_13_temp;
  C_14 <= C_14_temp;
  C_15 <= C_15_temp;
end Behavioral;
