-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n2_to_1_Mux is
  port (
    I_1: in std_logic;
    I_0: in std_logic;
    S_0: in std_logic;
    p_Out: out std_logic);
end n2_to_1_Mux;

architecture Behavioral of n2_to_1_Mux is
begin
  p_Out <= ((I_1 AND S_0) OR (I_0 AND NOT S_0));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8Bit_2_to_1_Mux is
  port (
    m_7: in std_logic;
    m_6: in std_logic;
    m_5: in std_logic;
    m_4: in std_logic;
    m_3: in std_logic;
    m_2: in std_logic;
    m_1: in std_logic;
    m_0: in std_logic;
    d_7: in std_logic;
    d_6: in std_logic;
    B_5: in std_logic;
    d_4: in std_logic;
    d_3: in std_logic;
    d_2: in std_logic;
    d_1: in std_logic;
    d_0: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic);
end n8Bit_2_to_1_Mux;

architecture Behavioral of n8Bit_2_to_1_Mux is
begin
  gate0: entity work.n2_to_1_Mux
    port map (
      I_1 => d_0,
      I_0 => m_0,
      S_0 => S_0,
      p_Out => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => d_1,
      I_0 => m_1,
      S_0 => S_0,
      p_Out => Out_1);
  gate2: entity work.n2_to_1_Mux
    port map (
      I_1 => d_2,
      I_0 => m_2,
      S_0 => S_0,
      p_Out => Out_2);
  gate3: entity work.n2_to_1_Mux
    port map (
      I_1 => d_3,
      I_0 => m_3,
      S_0 => S_0,
      p_Out => Out_3);
  gate4: entity work.n2_to_1_Mux
    port map (
      I_1 => d_4,
      I_0 => m_4,
      S_0 => S_0,
      p_Out => Out_4);
  gate5: entity work.n2_to_1_Mux
    port map (
      I_1 => B_5,
      I_0 => m_5,
      S_0 => S_0,
      p_Out => Out_5);
  gate6: entity work.n2_to_1_Mux
    port map (
      I_1 => d_6,
      I_0 => m_6,
      S_0 => S_0,
      p_Out => Out_6);
  gate7: entity work.n2_to_1_Mux
    port map (
      I_1 => d_7,
      I_0 => m_7,
      S_0 => S_0,
      p_Out => Out_7);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    S_0: in std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    M_Ovf: out std_logic;
    Rmdr: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
begin
  gate0: entity work.n8Bit_2_to_1_Mux
    port map (
      m_7 => In_6,
      m_6 => In_5,
      m_5 => In_4,
      m_4 => In_3,
      m_3 => In_2,
      m_2 => In_1,
      m_1 => In_0,
      m_0 => '0',
      d_7 => '0',
      d_6 => In_7,
      B_5 => In_6,
      d_4 => In_5,
      d_3 => In_4,
      d_2 => In_3,
      d_1 => In_2,
      d_0 => In_1,
      S_0 => S_0,
      Out_7 => Out_7,
      Out_6 => Out_6,
      Out_5 => Out_5,
      Out_4 => Out_4,
      Out_3 => Out_3,
      Out_2 => Out_2,
      Out_1 => Out_1,
      Out_0 => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => In_0,
      I_0 => In_7,
      S_0 => S_0,
      p_Out => s0);
  M_Ovf <= (s0 AND In_7);
  Rmdr <= (s0 AND In_0);
end Behavioral;
