-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n2_to_1_Mux is
  port (
    I_1: in std_logic;
    I_0: in std_logic;
    S_0: in std_logic;
    p_Out: out std_logic);
end n2_to_1_Mux;

architecture Behavioral of n2_to_1_Mux is
begin
  p_Out <= ((I_1 AND S_0) OR (I_0 AND NOT S_0));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16Bit_2_to_1_Mux is
  port (
    S_0: in std_logic;
    A_0: in std_logic;
    A_1: in std_logic;
    A_2: in std_logic;
    A_3: in std_logic;
    A_4: in std_logic;
    A_5: in std_logic;
    A_6: in std_logic;
    A_7: in std_logic;
    A_8: in std_logic;
    A_9: in std_logic;
    A_10: in std_logic;
    A_11: in std_logic;
    A_12: in std_logic;
    A_13: in std_logic;
    A_14: in std_logic;
    A_15: in std_logic;
    B_0: in std_logic;
    B_1: in std_logic;
    B_2: in std_logic;
    B_3: in std_logic;
    B_4: in std_logic;
    B_5: in std_logic;
    B_6: in std_logic;
    B_7: in std_logic;
    B_8: in std_logic;
    B_9: in std_logic;
    B_10: in std_logic;
    B_11: in std_logic;
    B_12: in std_logic;
    B_13: in std_logic;
    B_14: in std_logic;
    B_15: in std_logic;
    Out_0: out std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic);
end n16Bit_2_to_1_Mux;

architecture Behavioral of n16Bit_2_to_1_Mux is
begin
  gate0: entity work.n2_to_1_Mux
    port map (
      I_1 => B_0,
      I_0 => A_0,
      S_0 => S_0,
      p_Out => Out_0);
  gate1: entity work.n2_to_1_Mux
    port map (
      I_1 => B_1,
      I_0 => A_1,
      S_0 => S_0,
      p_Out => Out_1);
  gate2: entity work.n2_to_1_Mux
    port map (
      I_1 => B_2,
      I_0 => A_2,
      S_0 => S_0,
      p_Out => Out_2);
  gate3: entity work.n2_to_1_Mux
    port map (
      I_1 => B_3,
      I_0 => A_3,
      S_0 => S_0,
      p_Out => Out_3);
  gate4: entity work.n2_to_1_Mux
    port map (
      I_1 => B_4,
      I_0 => A_4,
      S_0 => S_0,
      p_Out => Out_4);
  gate5: entity work.n2_to_1_Mux
    port map (
      I_1 => B_5,
      I_0 => A_5,
      S_0 => S_0,
      p_Out => Out_5);
  gate6: entity work.n2_to_1_Mux
    port map (
      I_1 => B_6,
      I_0 => A_6,
      S_0 => S_0,
      p_Out => Out_6);
  gate7: entity work.n2_to_1_Mux
    port map (
      I_1 => B_7,
      I_0 => A_7,
      S_0 => S_0,
      p_Out => Out_7);
  gate8: entity work.n2_to_1_Mux
    port map (
      I_1 => B_8,
      I_0 => A_8,
      S_0 => S_0,
      p_Out => Out_8);
  gate9: entity work.n2_to_1_Mux
    port map (
      I_1 => B_9,
      I_0 => A_9,
      S_0 => S_0,
      p_Out => Out_9);
  gate10: entity work.n2_to_1_Mux
    port map (
      I_1 => B_10,
      I_0 => A_10,
      S_0 => S_0,
      p_Out => Out_10);
  gate11: entity work.n2_to_1_Mux
    port map (
      I_1 => B_11,
      I_0 => A_11,
      S_0 => S_0,
      p_Out => Out_11);
  gate12: entity work.n2_to_1_Mux
    port map (
      I_1 => B_12,
      I_0 => A_12,
      S_0 => S_0,
      p_Out => Out_12);
  gate13: entity work.n2_to_1_Mux
    port map (
      I_1 => B_13,
      I_0 => A_13,
      S_0 => S_0,
      p_Out => Out_13);
  gate14: entity work.n2_to_1_Mux
    port map (
      I_1 => B_14,
      I_0 => A_14,
      S_0 => S_0,
      p_Out => Out_14);
  gate15: entity work.n2_to_1_Mux
    port map (
      I_1 => B_15,
      I_0 => A_15,
      S_0 => S_0,
      p_Out => Out_15);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_RegCell is
  port (
    p_In: in std_logic;
    Clk: in std_logic;
    p_Out: out std_logic);
end n1Bit_RegCell;

architecture Behavioral of n1Bit_RegCell is
  signal s0: std_logic;
  signal s1: std_logic;
  signal Out_temp: std_logic;
begin
  s1 <= NOT (s0 AND NOT (Clk AND p_In));
  s0 <= NOT (NOT (Clk AND NOT p_In) AND s1);
  Out_temp <= NOT (NOT (s1 AND NOT Clk) AND NOT (Out_temp AND NOT (NOT Clk AND s0)));
  p_Out <= Out_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16Bit_AndArray is
  port (
    In_15: in std_logic;
    In_14: in std_logic;
    In_13: in std_logic;
    In_12: in std_logic;
    In_11: in std_logic;
    In_10: in std_logic;
    In_9: in std_logic;
    In_8: in std_logic;
    In_7: in std_logic;
    In_6: in std_logic;
    In_5: in std_logic;
    In_4: in std_logic;
    In_3: in std_logic;
    In_2: in std_logic;
    In_1: in std_logic;
    In_0: in std_logic;
    Rd: in std_logic;
    Out_2: out std_logic;
    Out_1: out std_logic;
    Out_0: out std_logic;
    Out_5: out std_logic;
    Out_4: out std_logic;
    Out_3: out std_logic;
    Out_8: out std_logic;
    Out_7: out std_logic;
    Out_6: out std_logic;
    Out_11: out std_logic;
    Out_10: out std_logic;
    Out_9: out std_logic;
    Out_14: out std_logic;
    Out_13: out std_logic;
    Out_12: out std_logic;
    Out_15: out std_logic);
end n16Bit_AndArray;

architecture Behavioral of n16Bit_AndArray is
begin
  Out_15 <= (In_15 AND Rd);
  Out_14 <= (In_14 AND Rd);
  Out_13 <= (In_13 AND Rd);
  Out_12 <= (In_12 AND Rd);
  Out_11 <= (In_11 AND Rd);
  Out_10 <= (In_10 AND Rd);
  Out_9 <= (In_9 AND Rd);
  Out_8 <= (In_8 AND Rd);
  Out_7 <= (In_7 AND Rd);
  Out_6 <= (In_6 AND Rd);
  Out_5 <= (In_5 AND Rd);
  Out_4 <= (In_4 AND Rd);
  Out_3 <= (In_3 AND Rd);
  Out_2 <= (In_2 AND Rd);
  Out_1 <= (In_1 AND Rd);
  Out_0 <= (In_0 AND Rd);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n16bit_Reg is
  port (
    In_1: in std_logic;
    Clk: in std_logic;
    Wrt: in std_logic;
    In_2: in std_logic;
    In_3: in std_logic;
    In_4: in std_logic;
    In_5: in std_logic;
    In_6: in std_logic;
    In_7: in std_logic;
    In_8: in std_logic;
    In_9: in std_logic;
    In_10: in std_logic;
    In_11: in std_logic;
    In_12: in std_logic;
    In_13: in std_logic;
    In_14: in std_logic;
    In_15: in std_logic;
    In_16: in std_logic;
    Rd: in std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic;
    Out_16: out std_logic);
end n16bit_Reg;

architecture Behavioral of n16bit_Reg is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
begin
  s0 <= (Wrt AND Clk);
  gate0: entity work.n1Bit_RegCell
    port map (
      p_In => In_1,
      Clk => s0,
      p_Out => s1);
  gate1: entity work.n1Bit_RegCell
    port map (
      p_In => In_2,
      Clk => s0,
      p_Out => s2);
  gate2: entity work.n1Bit_RegCell
    port map (
      p_In => In_3,
      Clk => s0,
      p_Out => s3);
  gate3: entity work.n1Bit_RegCell
    port map (
      p_In => In_4,
      Clk => s0,
      p_Out => s4);
  gate4: entity work.n1Bit_RegCell
    port map (
      p_In => In_5,
      Clk => s0,
      p_Out => s5);
  gate5: entity work.n1Bit_RegCell
    port map (
      p_In => In_6,
      Clk => s0,
      p_Out => s6);
  gate6: entity work.n1Bit_RegCell
    port map (
      p_In => In_7,
      Clk => s0,
      p_Out => s7);
  gate7: entity work.n1Bit_RegCell
    port map (
      p_In => In_8,
      Clk => s0,
      p_Out => s8);
  gate8: entity work.n1Bit_RegCell
    port map (
      p_In => In_9,
      Clk => s0,
      p_Out => s9);
  gate9: entity work.n1Bit_RegCell
    port map (
      p_In => In_10,
      Clk => s0,
      p_Out => s10);
  gate10: entity work.n1Bit_RegCell
    port map (
      p_In => In_11,
      Clk => s0,
      p_Out => s11);
  gate11: entity work.n1Bit_RegCell
    port map (
      p_In => In_12,
      Clk => s0,
      p_Out => s12);
  gate12: entity work.n1Bit_RegCell
    port map (
      p_In => In_13,
      Clk => s0,
      p_Out => s13);
  gate13: entity work.n1Bit_RegCell
    port map (
      p_In => In_14,
      Clk => s0,
      p_Out => s14);
  gate14: entity work.n1Bit_RegCell
    port map (
      p_In => In_15,
      Clk => s0,
      p_Out => s15);
  gate15: entity work.n1Bit_RegCell
    port map (
      p_In => In_16,
      Clk => s0,
      p_Out => s16);
  gate16: entity work.n16Bit_AndArray
    port map (
      In_15 => s16,
      In_14 => s15,
      In_13 => s14,
      In_12 => s13,
      In_11 => s12,
      In_10 => s11,
      In_9 => s10,
      In_8 => s9,
      In_7 => s8,
      In_6 => s7,
      In_5 => s6,
      In_4 => s5,
      In_3 => s4,
      In_2 => s3,
      In_1 => s2,
      In_0 => s1,
      Rd => Rd,
      Out_2 => Out_3,
      Out_1 => Out_2,
      Out_0 => Out_1,
      Out_5 => Out_6,
      Out_4 => Out_5,
      Out_3 => Out_4,
      Out_8 => Out_9,
      Out_7 => Out_8,
      Out_6 => Out_7,
      Out_11 => Out_12,
      Out_10 => Out_11,
      Out_9 => Out_10,
      Out_14 => Out_15,
      Out_13 => Out_14,
      Out_12 => Out_13,
      Out_15 => Out_16);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1Bit_FullAdder is
  port (
    A: in std_logic;
    B: in std_logic;
    C_in: in std_logic;
    S: out std_logic;
    C_out: out std_logic);
end n1Bit_FullAdder;

architecture Behavioral of n1Bit_FullAdder is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR C_in);
  C_out <= ((C_in AND s0) OR (A AND B));
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Clk: in std_logic;
    S_1: in std_logic;
    S_0: in std_logic;
    L_0: in std_logic;
    L_1: in std_logic;
    L_2: in std_logic;
    L_3: in std_logic;
    L_4: in std_logic;
    L_5: in std_logic;
    L_6: in std_logic;
    L_7: in std_logic;
    L_8: in std_logic;
    L_9: in std_logic;
    L_10: in std_logic;
    L_11: in std_logic;
    L_12: in std_logic;
    L_13: in std_logic;
    L_14: in std_logic;
    L_15: in std_logic;
    Out_0: out std_logic;
    Out_1: out std_logic;
    Out_2: out std_logic;
    Out_3: out std_logic;
    Out_4: out std_logic;
    Out_5: out std_logic;
    Out_6: out std_logic;
    Out_7: out std_logic;
    Out_8: out std_logic;
    Out_9: out std_logic;
    Out_10: out std_logic;
    Out_11: out std_logic;
    Out_12: out std_logic;
    Out_13: out std_logic;
    Out_14: out std_logic;
    Out_15: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal Out_0_temp: std_logic;
  signal Out_1_temp: std_logic;
  signal Out_2_temp: std_logic;
  signal Out_3_temp: std_logic;
  signal Out_4_temp: std_logic;
  signal Out_5_temp: std_logic;
  signal Out_6_temp: std_logic;
  signal Out_7_temp: std_logic;
  signal Out_8_temp: std_logic;
  signal Out_9_temp: std_logic;
  signal Out_10_temp: std_logic;
  signal Out_11_temp: std_logic;
  signal Out_12_temp: std_logic;
  signal Out_13_temp: std_logic;
  signal Out_14_temp: std_logic;
  signal Out_15_temp: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal s30: std_logic;
  signal s31: std_logic;
  signal s32: std_logic;
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
  signal s37: std_logic;
  signal s38: std_logic;
  signal s39: std_logic;
  signal s40: std_logic;
  signal s41: std_logic;
  signal s42: std_logic;
  signal s43: std_logic;
  signal s44: std_logic;
  signal s45: std_logic;
  signal s46: std_logic;
  signal s47: std_logic;
  signal s48: std_logic;
  signal s49: std_logic;
  signal s50: std_logic;
  signal s51: std_logic;
  signal s52: std_logic;
  signal s53: std_logic;
  signal s54: std_logic;
  signal s55: std_logic;
  signal s56: std_logic;
  signal s57: std_logic;
  signal s58: std_logic;
  signal s59: std_logic;
  signal s60: std_logic;
  signal s61: std_logic;
  signal s62: std_logic;
begin
  gate0: entity work.n16Bit_2_to_1_Mux
    port map (
      S_0 => S_1,
      A_0 => '1',
      A_1 => '0',
      A_2 => '0',
      A_3 => '0',
      A_4 => '0',
      A_5 => '0',
      A_6 => '0',
      A_7 => '0',
      A_8 => '0',
      A_9 => '0',
      A_10 => '0',
      A_11 => '0',
      A_12 => '0',
      A_13 => '0',
      A_14 => '0',
      A_15 => '0',
      B_0 => '1',
      B_1 => '1',
      B_2 => '1',
      B_3 => '1',
      B_4 => '1',
      B_5 => '1',
      B_6 => '1',
      B_7 => '1',
      B_8 => '1',
      B_9 => '1',
      B_10 => '1',
      B_11 => '1',
      B_12 => '1',
      B_13 => '1',
      B_14 => '1',
      B_15 => '1',
      Out_0 => s16,
      Out_1 => s19,
      Out_2 => s22,
      Out_3 => s25,
      Out_4 => s28,
      Out_5 => s31,
      Out_6 => s34,
      Out_7 => s37,
      Out_8 => s40,
      Out_9 => s43,
      Out_10 => s46,
      Out_11 => s49,
      Out_12 => s52,
      Out_13 => s55,
      Out_14 => s58,
      Out_15 => s61);
  gate1: entity work.n16bit_Reg
    port map (
      In_1 => s0,
      Clk => Clk,
      Wrt => '1',
      In_2 => s1,
      In_3 => s2,
      In_4 => s3,
      In_5 => s4,
      In_6 => s5,
      In_7 => s6,
      In_8 => s7,
      In_9 => s8,
      In_10 => s9,
      In_11 => s10,
      In_12 => s11,
      In_13 => s12,
      In_14 => s13,
      In_15 => s14,
      In_16 => s15,
      Rd => '1',
      Out_1 => Out_0_temp,
      Out_2 => Out_1_temp,
      Out_3 => Out_2_temp,
      Out_4 => Out_3_temp,
      Out_5 => Out_4_temp,
      Out_6 => Out_5_temp,
      Out_7 => Out_6_temp,
      Out_8 => Out_7_temp,
      Out_9 => Out_8_temp,
      Out_10 => Out_9_temp,
      Out_11 => Out_10_temp,
      Out_12 => Out_11_temp,
      Out_13 => Out_12_temp,
      Out_14 => Out_13_temp,
      Out_15 => Out_14_temp,
      Out_16 => Out_15_temp);
  gate2: entity work.n1Bit_FullAdder
    port map (
      A => Out_0_temp,
      B => s16,
      C_in => '0',
      S => s17,
      C_out => s18);
  gate3: entity work.n1Bit_FullAdder
    port map (
      A => Out_1_temp,
      B => s19,
      C_in => s18,
      S => s20,
      C_out => s21);
  gate4: entity work.n1Bit_FullAdder
    port map (
      A => Out_2_temp,
      B => s22,
      C_in => s21,
      S => s23,
      C_out => s24);
  gate5: entity work.n1Bit_FullAdder
    port map (
      A => Out_3_temp,
      B => s25,
      C_in => s24,
      S => s26,
      C_out => s27);
  gate6: entity work.n1Bit_FullAdder
    port map (
      A => Out_4_temp,
      B => s28,
      C_in => s27,
      S => s29,
      C_out => s30);
  gate7: entity work.n1Bit_FullAdder
    port map (
      A => Out_5_temp,
      B => s31,
      C_in => s30,
      S => s32,
      C_out => s33);
  gate8: entity work.n1Bit_FullAdder
    port map (
      A => Out_6_temp,
      B => s34,
      C_in => s33,
      S => s35,
      C_out => s36);
  gate9: entity work.n1Bit_FullAdder
    port map (
      A => Out_7_temp,
      B => s37,
      C_in => s36,
      S => s38,
      C_out => s39);
  gate10: entity work.n1Bit_FullAdder
    port map (
      A => Out_8_temp,
      B => s40,
      C_in => s39,
      S => s41,
      C_out => s42);
  gate11: entity work.n1Bit_FullAdder
    port map (
      A => Out_9_temp,
      B => s43,
      C_in => s42,
      S => s44,
      C_out => s45);
  gate12: entity work.n1Bit_FullAdder
    port map (
      A => Out_10_temp,
      B => s46,
      C_in => s45,
      S => s47,
      C_out => s48);
  gate13: entity work.n1Bit_FullAdder
    port map (
      A => Out_11_temp,
      B => s49,
      C_in => s48,
      S => s50,
      C_out => s51);
  gate14: entity work.n1Bit_FullAdder
    port map (
      A => Out_12_temp,
      B => s52,
      C_in => s51,
      S => s53,
      C_out => s54);
  gate15: entity work.n1Bit_FullAdder
    port map (
      A => Out_13_temp,
      B => s55,
      C_in => s54,
      S => s56,
      C_out => s57);
  gate16: entity work.n1Bit_FullAdder
    port map (
      A => Out_14_temp,
      B => s58,
      C_in => s57,
      S => s59,
      C_out => s60);
  gate17: entity work.n1Bit_FullAdder
    port map (
      A => Out_15_temp,
      B => s61,
      C_in => s60,
      S => s62);
  gate18: entity work.n16Bit_2_to_1_Mux
    port map (
      S_0 => S_0,
      A_0 => s17,
      A_1 => s20,
      A_2 => s23,
      A_3 => s26,
      A_4 => s29,
      A_5 => s32,
      A_6 => s35,
      A_7 => s38,
      A_8 => s41,
      A_9 => s44,
      A_10 => s47,
      A_11 => s50,
      A_12 => s53,
      A_13 => s56,
      A_14 => s59,
      A_15 => s62,
      B_0 => L_0,
      B_1 => L_1,
      B_2 => L_2,
      B_3 => L_3,
      B_4 => L_4,
      B_5 => L_5,
      B_6 => L_6,
      B_7 => L_7,
      B_8 => L_8,
      B_9 => L_9,
      B_10 => L_10,
      B_11 => L_11,
      B_12 => L_12,
      B_13 => L_13,
      B_14 => L_14,
      B_15 => L_15,
      Out_0 => s0,
      Out_1 => s1,
      Out_2 => s2,
      Out_3 => s3,
      Out_4 => s4,
      Out_5 => s5,
      Out_6 => s6,
      Out_7 => s7,
      Out_8 => s8,
      Out_9 => s9,
      Out_10 => s10,
      Out_11 => s11,
      Out_12 => s12,
      Out_13 => s13,
      Out_14 => s14,
      Out_15 => s15);
  Out_0 <= Out_0_temp;
  Out_1 <= Out_1_temp;
  Out_2 <= Out_2_temp;
  Out_3 <= Out_3_temp;
  Out_4 <= Out_4_temp;
  Out_5 <= Out_5_temp;
  Out_6 <= Out_6_temp;
  Out_7 <= Out_7_temp;
  Out_8 <= Out_8_temp;
  Out_9 <= Out_9_temp;
  Out_10 <= Out_10_temp;
  Out_11 <= Out_11_temp;
  Out_12 <= Out_12_temp;
  Out_13 <= Out_13_temp;
  Out_14 <= Out_14_temp;
  Out_15 <= Out_15_temp;
end Behavioral;
