-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    toggle: in std_logic;
    IN_7: in std_logic;
    IN_6: in std_logic;
    IN_5: in std_logic;
    IN_4: in std_logic;
    IN_3: in std_logic;
    IN_2: in std_logic;
    IN_1: in std_logic;
    IN_0: in std_logic;
    OUT_7: out std_logic;
    OUT_6: out std_logic;
    OUT_5: out std_logic;
    OUT_4: out std_logic;
    OUT_3: out std_logic;
    OUT_2: out std_logic;
    OUT_1: out std_logic;
    OUT_0: out std_logic);
end main;

architecture Behavioral of main is
begin
  OUT_0 <= (IN_0 XOR toggle);
  OUT_1 <= (IN_1 XOR toggle);
  OUT_2 <= (IN_2 XOR toggle);
  OUT_3 <= (IN_3 XOR toggle);
  OUT_4 <= (IN_4 XOR toggle);
  OUT_5 <= (IN_5 XOR toggle);
  OUT_6 <= (IN_6 XOR toggle);
  OUT_7 <= (IN_7 XOR toggle);
end Behavioral;
